name: Accept PR on Tag

on:
  pull_request:
    types:
      - labeled

jobs:
  accept_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check if labeled with "wikis pr" tag
        run: |
          echo "Tag: ${{ github.event.label.name }}"
          if [[ "${{ github.event.label.name }}" == "wikis pr" ]]; then
            echo "Tag 'wikis pr' found!"
            exit 0
          else
            echo "Tag 'wikis pr' not found. Exiting..."
            exit 1
          fi

      - name: Accept PR
        if: ${{ success() }}
        run: |
          echo "Accepting PR..."
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          PR_NUMBER="${{ github.event.pull_request.number }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/merge"
          curl -X PUT -H "Authorization: Bearer ${TOKEN}" ${API_URL}
